# site settings
title: Pulsipher
subtitle: Info
email: pulsipher@uwaterloo.ca
description: Assistant Professor of Chemical Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: https://pulsipher.github.io # the base hostname & protocol for your site
author: pulsipher
university: University of Waterloo
room: Engineering 6, Room 5008
street_address: 200 University Avenue West
city: Waterloo
state: Ontario
zip_code: N2L 3G1
country: Canada
formspreeEndpoint: https://formspree.io/f/xaykpvzo
branch: master
repo: pulsipher/pulsipher.github.io
google_analytics: G-MCGJLE9DXE
phone: +1 (519) 888-4567 ext. 42290

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 8

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/pulsipher
  LinkedIn: https://www.linkedin.com/in/joshua-pulsipher
  Twitter: https://twitter.com/pulsipher42
  # Facebook: https://www.facebook.com/appsparkler

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
